name: Build pnpm package and Publish
description: |
  pnpm の npm パッケージを ./dist にビルドし
  npmjs に公開します。
  run-script の `prepublishOnly` にリント、ビルド、テストが含まれていることを想定。

inputs:
  checkout:
    description: |
      リポジトリをチェックアウトするかどうか
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: inputs.checkout == 'true'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
        persist-credentials: false

    - name: Setup pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        version: 10
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: "lts/*"
        cache: pnpm

    # - run: npm install -g npm@latest
    # 最近はおおむね不要. nodeの最新LTS版バンドルnpmで十分

    - name: "INFO: Show versions of Node.js, npm, and pnpm"
      shell: bash
      run: node -v && npm -v && pnpm -v

    - name: "INFO: Show .npmrc (if exists)"
      # actions/setup-node で自動生成される .npmrc の中身を確認する
      shell: bash
      run: test -n "${NPM_CONFIG_USERCONFIG}" && test -f "${NPM_CONFIG_USERCONFIG}" && cat "${NPM_CONFIG_USERCONFIG}" || echo "NPM_CONFIG_USERCONFIG not found"
      ## 今回は registry-url: も scope: も指定していないので .npmrc は自動生成されない

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    # - run: npm run build --if-present
    # - run: npm test
    ## このプロジェクトでは prepublishOnly に書いてあるので不要

    - name: Show whether this is a pre-release or stable release
      shell: bash
      run: |
        if [[ $GITHUB_REF_NAME == *-* ]]; then
          echo "TAG=dev" >> "${GITHUB_ENV}"
        else
          echo "TAG=latest" >> "${GITHUB_ENV}"
        fi

    - name: Publish to npm via OIDC (Trusted publishing)
      shell: bash
      run: npm publish --access public --tag "${TAG}"
      env:
        NODE_AUTH_TOKEN: "" # 念のため


# # おまけ。releases にもtgzをアップロードする
# - name: build package
#   run: pnpm run build
# - name: Pack package tarball
#   run: pnpm pack
# - name: Create GitHub Release
#   uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
#   with:
#     files: ./*.tgz
#     generate_release_notes: true
#     prerelease: ${{ contains(github.ref_name, '-') }}
#   env:
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
